import Head from 'next/head';
import s from './Layout.module.scss';

type Props = {
  title:string;
  header: React.ReactNode;
  children: React.ReactNode;
  footer: React.ReactNode;
};

export function Layout({
  title, header, children, footer,
} : Props) : JSX.Element {
  return (
    <div className={s.layout}>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={s.layout__header}>
        {header}
      </header>
      <main className={s.layout__main}>
        {children}
      </main>
      <footer className={s.layout__footer}>
        {footer}
      </footer>
    </div>
  );
}
