import type { NextPage } from 'next';
import Head from 'next/head';
import Link from 'next/link';
import styles from '../styles/Home.module.css';
import AddToCart from '../components/AddToCartButton'

type Props = any;

const Menu: NextPage = ({ categories, menu }: any) => (

    <div className={styles.container}>
      <Head>
        <title>Menu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <p>Hér verður menu</p>

        <AddToCart />
          <ul>
            {categories.items.map((item: any, i:number) => (
                <Link key={i} href={`/categories/${item.id.toString()}`}>
                  <li >{item.title}</li>
                </Link>
            ))}
          </ul>

          <ul>
            {menu.items.map(function(item: any, i:number){
              return(
                  <li key={i}>{item.title}</li>
              )
            })}
          </ul>
      </main>
    </div>
);
export async function getServerSideProps() {
  const categoriesRes = await fetch('https://vef2-2022-h1-synilausn.herokuapp.com/categories');
  const categories = await categoriesRes.json();
  const menuRes = await fetch('https://vef2-2022-h1-synilausn.herokuapp.com/menu');
  const menu = await menuRes.json();
  return { props: { categories, menu } };
}

export default Menu;
